/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#f0f2ff',
        'secondary-container': '#00d4ff',
        error: '#ff2e63',
        tertiary: '#ff00e5',
        'surface-dim': '#020617',
        primary: '#b026ff',
        background: '#020617',
        'primary-container': '#7b00ff',
        'surface-container-high': '#0f172a',
        'on-primary-fixed-variant': '#ffffff',
        'on-secondary': '#000000',
        'on-primary': '#ffffff',
        'error-container': '#6a001a',
        outline: '#475569',
        'on-tertiary-container': '#ffffff',
        surface: '#020617',
        'on-primary-container': '#ffffff',
        'tertiary-container': '#d400ff',
        'primary-dim': '#d49eff',
        'on-secondary-fixed-variant': '#00e5ff',
        'tertiary-dim': '#f780ff',
        'tertiary-fixed-dim': '#f780ff',
        'primary-fixed': '#e2cbff',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#070e1e',
        'secondary-fixed': '#a1f2ff',
        'on-secondary-fixed': '#000000',
        'on-tertiary-fixed': '#000000',
        'on-error-container': '#ffb2b9',
        'on-tertiary': '#ffffff',
        'surface-variant': '#1e293b',
        'on-primary-fixed': '#000000',
        'on-surface-variant': '#94a3b8',
        'inverse-primary': '#7b00ff',
        'on-secondary-container': '#000000',
        'outline-variant': '#334155',
        'secondary-dim': '#00d4ff',
        'tertiary-fixed': '#ff9eff',
        'inverse-on-surface': '#020617',
        'surface-tint': '#b026ff',
        'error-dim': '#ff4d7a',
        'surface-container': '#0b1120',
        'on-surface': '#f8fafc',
        'inverse-surface': '#f8fafc',
        'primary-fixed-dim': '#b026ff',
        secondary: '#00e5ff',
        'surface-bright': '#1e293b',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#ffffff',
        'secondary-fixed-dim': '#00d4ff',
        'surface-container-highest': '#1e293b',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
